version: "3"

services:
  mariadb:
    # build: ./server/bin/mariadb
    image: mariadb
    container_name: christmasinvite-mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=christmasinvite
      - MYSQL_USER=christmasinvite
      - MYSQL_PASSWORD=christmasinvite
      - MYSQL_ROOT_PASSWORD=christmasinvite
    volumes:
      - ./server/logs/mysql:/var/log/mysql
      - ./server/data/mariadb:/var/lib/mysql
      - ./server/config/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
  flyway:
    container_name: flyway
    image: boxfuse/flyway:5.2.4
    command: -url=jdbc:mysql://christmasinvite-mariadb/christmasinvite -schemas=christmasinvite -user=christmasinvite -password=christmasinvite -connectRetries=60 migrate
    volumes:
      - ./server/migrations:/flyway/sql
    links:
      - mariadb
    depends_on:
      - mariadb
  # redis:
  #   container_name: 'redis'
  #   image: redis:latest
  #   ports:
  #     - "6379:6379"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'phpmyadmin'
    links:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    ports:
      - '8888:80'
    volumes:
      - /sessions
    links:
      - mariadb
    depends_on:
      - mariadb
  webserver:
    build:
      context: ./server/bin/webserver-php7
    container_name: 'webserverphp7'
    #   context: ./server/bin/webserver-php56
    # container_name: 'webserverphp56'
    restart: 'always'
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./server/config/php/php.ini:/usr/local/etc/php/php.ini
      - ./server/config/vhosts:/etc/apache2/sites-enabled
      - ./server/logs/apache2:/var/log/apache2
    links:
      - mariadb
    depends_on:
      - flyway
